### ISSUE TITLE
How to submit zcee to openhw ？

### ISSUE THREAD

**Issue by Liaoshihua** [openhwgroup/corev-gcc#2]
Hello，
         I had implemented zcee extension based on riscv-gcc-10.2.0 in last month, and how can I submit it into the designated branch of openhw ?

**Comment by jeremybennett** [comment]
@Liaoshihua That's great news. You'll first need to add your instructions to the GNU assembler and any relocations to the GNU linker in the [corev-binutils-gdb](https://github.com/openhwgroup/corev-binutils-gdb) repository. Here is what you need to do.

1. Ensure you have an Eclipse Committer's Agreement in place and it is linked to your GitHub ID. This is because OpenHW is a project of the Eclipse Foundation.

2. Rebase your assembler and linker work on the `development` branch of the [corev-binutils-gdb](https://github.com/openhwgroup/corev-binutils-gdb) repository, ensuring all your commits are signed using the email address associated with your GitHub ID. (use `git commit -s ...`). The development branch is based on upstream top-of-tree, but we only roll it forward every few months, so it is slightly behind.

3. Ensure your work includes comprehensive assembler tests for any instructions you have added and linker tests for any relocations you have added.  Run regression testing of the GNU assembler and GNU linker, and ensure you have not introduced any new failures or unresolved tests. Put your ChangeLog messages into files named `ChangeLog.COREV` and follow [GNU ChangeLog guidelines](https://www.gnu.org/prep/standards/html_node/Change-Logs.html)

4. Submit a pull-request to  [corev-binutils-gdb](https://github.com/openhwgroup/corev-binutils-gdb) and ask @jessicamills to review it. In the comment for the commit, follow GNU ChangeLog guidelines, since these will be required for ustreaming. It is helpful to add a comment with your regression test results.

5. Then for GCC, rebase your work on the `development` branch of the [corev-gcc](https://github.com/openhwgroup/corev-gcc) repository, ensuring all your commits are signed using the email address associated with your GitHub ID. (use `git commit -s ...`). The development branch is based on upstream GCC's top-of-tree, but we only roll it forward every few months, so it is slightly behind.

6. Ensure your work includes comprehensive tests for the work you have added, including execution tests for any instruction added to the assembler, using inline assembly.  Ensure you have not introduced any new failures or unresolved tests.  Put your ChangeLog messages into files named `ChangeLog.COREV` and follow [GNU ChangeLog guidelines](https://www.gnu.org/prep/standards/html_node/Change-Logs.html)

7. Submit a pull-request to  [corev-gcc](https://github.com/openhwgroup/corev-gcc) and ask @jessicamills to review it. In the comment for the commit, follow GNU ChangeLog guidelines, since these will be required for upstreaming. It is helpful to add a comment with your regression test results.

Hope this is helpful. Don't hesitate to ask for help on the OpenHW Group Mattermost - there is a dedicated channel for the GNU tools project.

**Comment by jessicamills** [comment]
@Liaoshihua I have just rolled forward CORE-V GCC, so whenever you are ready you can rebase and submit a pull request. Thanks

**Comment by Liaoshihua** [comment]
Thanks,
    I will PR zcee after I have rebased them.
