### ISSUE TITLE
Post-inc memory access generation for -Os -Oz and -Og

### ISSUE THREAD

**Issue by jeremybennett** [openhwgroup/corev-gcc#58]
The support for post-increment addressing in #57 does not generate these instructions for `-Os`, `-Oz` or `-Og`.  This issues captures the need to add this functionality.

**Comment by craigblackmore** [comment]
For https://github.com/openhwgroup/corev-gcc/blob/035c7190d3f89e5f96bf87f5b1030f76ea62f89d/gcc/testsuite/gcc.target/riscv/cv-mem-lw-compile-1.c,  gcc `-Os` and `Oz` does not generate code that is amenable to transforming to post inc. This is due to:

https://github.com/openhwgroup/corev-gcc/blob/035c7190d3f89e5f96bf87f5b1030f76ea62f89d/gcc/tree-ssa-loop-ch.cc#L420-L432

You could try changing the loop limit in the test to a compile time constant e.g. change `i<n` to `i<200`.

**Comment by MaryBennett** [comment]
Thank you, changing from n to 200 works if the c extension is included. I'll add this for cv-mem-*-compile-[1,2].c.

**Comment by MaryBennett** [comment]
For now, we will mark Os, Oz, and Og as UNSUPPORTED.

**Comment by MaryBennett** [comment]
Could the volatile key word help?

**Comment by MaryBennett** [comment]
> Thank you, changing from n to 200 works if the c extension is included. I'll add this for cv-mem-*-compile-[1,2].c.

This is done in PR #96.
It does not change the need for Og.

**Comment by MaryBennett** [comment]
Moved to new issue #108
